### ISSUE TITLE
we should not directly put secret payload in the manifests field

### ISSUE THREAD

**Issue by qiujian16** [open-cluster-management-io/work#114]
There are security concern since secret in kube is stores in different way and can be encrypted which can not be done if its content is in the manifestwork. 

This is the community discussion https://kubernetes.slack.com/archives/C01GE7YSUUF/p1641473993005700

/kind feature
/assign @qiujian16

**Comment by jnpacker** [comment]
What about a binding customer resource in the `ManagedCluster` namespace, that would move specific secrets to a location.
1. You can restrict access to this custom resource
2. You don't need to grant a user direct access to the secret
3. The scope is limited to the Managed Cluster namespace

RBAC
Today the persona with access to the ManagedCluster namespace is the Cluster Administrator, so this is not really a privilege elevation.
