### ISSUE TITLE
What is the AppliedMainfestWork for? 

### ISSUE THREAD

**Issue by siyu618** [open-cluster-management-io/work#116]
In the code, there are MainfestWork and AppliedMainfestWork. 
Why do we need both of them? 
What is the purpose of this design?   Is it for deletion when managed cluster unjoined from hub cluster?

**Comment by qiujian16** [comment]
yes, appliedmanifestwork is an internal API on spoke to record what resources have been applied by a manifestwork. We also set the ownerref from appliedmanifestwork to all resources managed by manifestworks. So when an appliedmanifestwork is deleted, all related resources will also be cleaned.
