### ISSUE TITLE
How to apply a workload to many clusters? Do I have to create multiple ManifestWorks?

### ISSUE THREAD

**Issue by mrningyang** [open-cluster-management-io/work#125]
If i want to apply a deployment to cluster a and b, do I have to create two ManifestWorks to apply the deployment to cluster a and cluster b? If i want to update the workload, do I have to update all the ManifestWorks about the workload?

**Comment by thehackercat** [comment]
no, you don't

**Comment by xuctom** [comment]
use placement

**Comment by qiujian16** [comment]
/close

this repo is going to be archived, please create an issue in ocm repo
