### ISSUE TITLE
AppliedManifestWorkFinalizeController may need to be added a hubhash filter

### ISSUE THREAD

**Issue by TYTaO** [open-cluster-management-io/work#150]
Like other controllers in this project, appliedManifestWorkFinalizeController may also need the hubhash filter to avoid conflicts in the case of multiple hub.
https://github.com/open-cluster-management-io/work/blob/61c038e3f35a770cc4736689a9a491f4b0fcb5ed/pkg/spoke/controllers/finalizercontroller/appliedmanifestwork_finalize_controller.go

**Comment by qiujian16** [comment]
this is done already. 

/close
