### ISSUE TITLE
Manifest size limit

### ISSUE THREAD

**Issue by fgiloux** [open-cluster-management-io/work#185]
I am wondering where the 50k limit comes from:
https://github.com/open-cluster-management-io/work/blob/main/pkg/webhook/manifestwork_webhook.go#L26-L27

[etcd default size limit](https://etcd.io/docs/v3.5/dev-guide/limit/) for request is 1.5MB
[kubernetes limit for configMaps](https://kubernetes.io/docs/concepts/configuration/configmap/#motivation) or secrets is 1MB

It means that ManifestWork cannot be used for large CRDs or ConfigMaps. This results in errors like:
~~~
E0221 09:04:14.759235       1 base_controller.go:159] "addon-deploy-controller" controller failed to sync "cluster1/olm-addon", err: [admission webhook "manifestworkvalidators.admission.work.open-cluster-management.io" denied the request: manifests should not be empty, admission webhook "manifestworkvalidators.admission.work.open-cluster-management.io" denied the request: the size of manifests is 269941 bytes which exceeds the 50k limit, admission webhook "manifestworkvalidators.admission.work.open-cluster-management.io" denied the request: the size of manifests is 99458 bytes which exceeds the 50k limit]
~~~

Also I am not sure of the value of this check. If the ManifestWork resource is too large, an error will get returned. What added value does the error returned by the validation webhook provide?

**Comment by qiujian16** [comment]
Currently 50k is just a guess. We need the validation because in addition to manifests, we also record applied/available status of each manifest and optionally some status field of the applied resource if the user configure it. If a user create a manifestwork with a very large manifets, it is possible, that creating it succeeds, but agent cannot update its status.

We had an issue tracked before to allow configuring the size limit on manifestworks. FYI @zhiweiyin318

**Comment by qiujian16** [comment]
https://github.com/open-cluster-management-io/addon-framework/issues/116 one of the fix we did is if you have several manifests and the total size is larger than 50k, it will be put into multiple manifestworks by addon-framework library using a bin-packing approach.

**Comment by fgiloux** [comment]
[slack thread](https://kubernetes.slack.com/archives/C01GE7YSUUF/p1677510984910089)

**Comment by qiujian16** [comment]
discussed with @zhiweiyin318 we will just change the threshold to 500k as the first step. In the following step, provide a flag so user can set the limit size. Long term we need to treat crd resources in a better approach, it would bring many duplicated data on hub if there are many clusters. Maybe a work template resource that can be referenced by the manifestwork, so we do not need to copy the data across multiple namespaces.

**Comment by fgiloux** [comment]
ack

**Comment by zhiweiyin318** [comment]
@fgiloux  the pr was merged, please try the latest image for your case.

**Comment by fgiloux** [comment]
@zhiweiyin318 I have tied the latest image and it fixed my issue. Thanks for the swift way you have addressed this request.

I still think there is value for an approach that is accepting any valid Kubernetes manifest. When you develop an application with open cluster management in mind you can surely design it with the 500k restriction. I would however argue that most of the application authors would not have that on their radar. Most of them may not even know of it. For people, who are users of such applications and try to deploy them thanks to open cluster management it may be a large burden, if possible at all, to shoehorn the manifests within the 500k limit with each and every release.
