### ISSUE TITLE
Request that manifestWork conditions carry the `ObservedGeneration` of the ManifestWork

### ISSUE THREAD

**Issue by ShyamsundarR** [open-cluster-management-io/work#83]
At the hub, we create and later update certain ManifestWork CRs. Our reconciler hence needs to check if the latest generation of the ManifestWork is applied, before progressing on its tasks.

Without the `ObserveredGeneration` it is not possible to parse if the conditions are stale and hence for the older generation of the work CR or is for the most recent generation.

As the current implementation of ManifestWork does not report `ObserverGeneration` in its conditions, the request is to add the same.

**Comment by qiujian16** [comment]
good catch! we will queue this as an enhancement.

/assign @qiujian16

**Comment by qiujian16** [comment]
it is done
